language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: px4+kRBQRtZNYZy0eYcitJZxMsOJfEniZ+zN8cFbwfMyJVcuSFFOI9QCb2lpy16pLdtI5NntfgEaaOCpBSXsMQW/FOgm+yc45i9mJOCsAnE0xj7WwX3r4P/4XsIlHT8S9zLAYeH2QeBmOoSuYvXfQoNphk7sY8sHWdWZPu39qqo/1qn7DPML2rBIXnVs0h7dQw4C9o3QJVsmf4r4hb+1l7G6aWiQn4kg5EBpwJUciwWlzrgsa4Q6Lu28RP1oAFwX8m0vlI5jVwpQAM9HRx51YMFWpAg07alx7Bs0AG7zhQ2go9Lxgyly1aO/3IVu82qSzHhsw3o4OwWhiabdS5vtxYhGRwgPrb9lWZpHhJpZPuXwaPzOL4zkhl0SVJzZjQOmJcryAYVIF8X8hIuNzzXtma4v0TXc38Myqsw1l3Yo6fF7qkZNfOJMoB6U9ljzfBET0O/Oeysb2t6mx5WGbkYvjX/GZxGZdl5fbIaphtraFsu2uIZ5aITWl/1MHOA0sBBGNQtvuPOwSoEUQs/Iko0pp8sTeeZZ8kUo/sU3FKIIUo09DTPQnyk/AKYGXYeGs50WJT8P53V2vvqnxVMDTdW8pbllZHTEnZvc1xSDvZ9xR3mTNBaEvTZSZOJXgVEyM9BQXb3fKPl828vkOmoNd4E6op3rG0wSibD2zp6+CZwYflg=
  app: node-restaurants-app-mongoose
  on:
    repo: bdm88/node-restaurants-app-mongoose
    branch: feature/with-tests
