language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Pfj5RgalYUkQPSJ4FffnWXm6zas31vQF1BO877eZl0mqEKa/lWqDEMzeMQFMKd53g45rX49MhhWGTS0T3XWuxj16YAYnC6G1n8rNVnXupXjK4JogeUQTsH0MFQITLPJ+Rd6bDy+f8dLLE+suRerflhGTJ0EAfI45UdC2IxykjXQ4eoerFHH0JzTNuCgNGPulbJHT6oiXZ4l/18lLRv47DXA8nlTHotn/CYdkmQ1ASg2a7J2ghmHy4y4xg+8cQnKC/jMXoaKRj3DzLHO1AJlYG8pFsDdhnYq5IaB4MIzlqOh5nYR34ftAZbTa3O7rRQs0bRndrkH5DW2LEfwRy+AlAC8ZDQJPf9UjLp0ArHxo7kQVLiM2zHzZ3UabWBlfRUyQByzJHrNcU2DTI5oIsSEJJ2wW1iVqTetzaptyTkdCiBBTEqDlIw0KZMyW1Ftl5X16YlBHE3YdTGYi0/JP8PsO/DJGV9kZIiDAUydhv6x7CVpg8XAYcHJAVpRd35IV1NgJxfCb76jisZ/WN+jKPUCoP8mdX9OpGFaHxrtj8pSdk/Rglk1wCr0NljaE8a8wAjVPgEgeA7BZhcjU1W2pXndnhugGmz1G/XCnE417jvE1pN3iu0s8bXdL3FUBqZXivGUKNslNC3IZREhVnvqKLo4GTI2+1Tjtsf7tXyH8akhtHo0=
  app: node-restaurants-app-mongoose
  on:
    repo: bdm88/node-restaurants-app-mongoose
    branch: feature/with-tests
